### ISSUE TITLE
Does not work with <a name=""> anchors

### ISSUE THREAD

**Issue by bannmann** [certainlyakey/Copy-current-page-URL-with-anchor#1]
The addon does not support classic `<a name="">` anchors at all.

To my knowledge, instead of nesting stuff inside the `<a>` element, real world pages mostly use these by including an anchor _inside the heading element_ like this:

```
<h1>This is a nice heading<a name="nice_heading"></a></h1>
```

An example of this technique can be seen [here](http://www.mojohaus.org//build-helper-maven-plugin/usage.html).

**Comment by certainlyakey** [comment]
You're right. I'll see if I can add this in near future.
