### ISSUE TITLE
Port to WebExtensions API

### ISSUE THREAD

**Issue by kernc** [certainlyakey/Copy-current-page-URL-with-anchor#2]
Please consider porting this awesome add-on to [WebExtension API](https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Getting_Started_with_Firefox_Extensions), the only add-on API supported in Firefox 57+ (and Chrome etc.).

**Comment by kernc** [comment]
Would you review/accept a PR with this effort?

**Comment by certainlyakey** [comment]
Yes I would, could be awesome. Thanks for the suggestion and glad you liked it!
