### ISSUE TITLE
Doesn't work currently

### ISSUE THREAD

**Issue by irvnriir** [certainlyakey/Copy-current-page-URL-with-anchor#4]

**Comment by kernc** [comment]
Seems to work for me in Firefox 78. Can you give an example webpage / steps to show how it doesn't work?

**Comment by irvnriir** [comment]
Any page

`Debug Add-ons \ [addon] \ Inspector`, https://en.wikipedia.org/wiki/Wikipedia :

![Screenshot](https://user-images.githubusercontent.com/13949704/120230403-ba0b5d80-c23e-11eb-9185-48287ebe2d16.png)

**Comment by kernc** [comment]
Are you sure this is related to our extension? Nothing in the two brief stack traces indicates as much. This is [its whole code](https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/blob/master/content.js), and we never touch anything cookie-related ...

**Comment by irvnriir** [comment]
@kernc when i tried running it alone in Private it didn't work . the errors isn't shown in Dev Tool 's (global) Console, so logically they result from the extension . did you try the last Firefox and loading it from https://addons.mozilla.org/en-US/firefox/addon/copy-with-anchor/ ? also, may i misunderstand that it doesn't have specific requirements for the click location ?

**Comment by kernc** [comment]
> specific requirements for the click location

It _does_. It only works on elements that follow `a[name]`:
https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/blob/6641750737342348267aa74300956c4a0755798e/content.js#L48-L49
elements that _contain_ `a[name]`:
https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/blob/6641750737342348267aa74300956c4a0755798e/content.js#L57-L59
and various elements that declare `id=`:
https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/blob/6641750737342348267aa74300956c4a0755798e/content.js#L67-L72

I was thinking for a while now it might also work on `h1[id] ~ p` (with `h1[id]` really any from the above list).

**Comment by irvnriir** [comment]
if you mean "<a" should work, then no change .

can you show an img of it working on the https://en.wikipedia.org/wiki/Wikipedia ?

**Comment by kernc** [comment]
`<a name="..."` or `<a id="...">`, not just any regular `<a>`.

![Screenshot_2021-06-01_02-48-01](https://user-images.githubusercontent.com/684364/120252277-57d54b80-c284-11eb-9db6-10caf677d48b.png)


This is on Firefox 78.

**Comment by irvnriir** [comment]
Well, on **88**, on Windows it doesn't work .

**Comment by kernc** [comment]
For lack of better immediate idea, maybe it has something to do with missing [`permissions` key in _manifest.json_](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions). There seems to be a permission to request for `contextMenus`. :thinking:

**Comment by papuSpartan** [comment]
Can't seem to get it to work either. I'm using Firefox 92.0a1. This is what's showing in the addon debugger: [image](https://i.imgur.com/ER34hKm.png)

**Comment by kernc** [comment]
Only now came around to using Firefox 91 ESR and took time to look into it. A supposed fix in https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/pull/7. Welcome to test, everyone.

**Comment by bb010g** [comment]
Firefox put support for `<menuitem>` behind a flag in Firefox 85 (Firefox ESR 91 (release date 2021-08-10 (alongside Firefox ESR 78 until 2021-11-02)), after it was dropped from the WHATWG HTML specification, and has completely dropped support in Firefox 103 (will completely drop support in Firefox ESR 115 (scheduled release date 2023-07-04 (alongside Firefox ESR 102 until 2023-09-26)).

* https://html.spec.whatwg.org/commit-snapshots/942a9d5b9c0b50bf5bca275e866bb2319ebdca0c/#the-menu-element
* <https://github.com/whatwg/html/issues/2730>
  * <https://github.com/whatwg/html/pull/2742>
  * <https://github.com/whatwg/html/commit/e7e8c88ecdd7cdc96171f05ab6fe23b56dd48d8a>
* Bug 617528 - **implement the HTML5 "context menu" feature (contextmenu attribute)** (Opened: 2010-12-08; Closed: 2012-02-08; Status: RESOLVED; Resolution: FIXED; Target Milestone: mozilla8): <https://bugzilla.mozilla.org/show_bug.cgi?id=617528>
* Bug 1680596 - **Hide \<menuitem\> behind a flag** (Opened: 2020-12-03; Closed: 2020-12-09; Status: RESOLVED: Resolution: FIXED; Target Milestone: 85 Branch): <https://bugzilla.mozilla.org/show_bug.cgi?id=1680596>
  * [Bug 1680596](https://bugzilla.mozilla.org/show_bug.cgi?id=1680596) - Part 1: Hide \<menuitem\> behind a flag r=smaug: <https://hg.mozilla.org/mozilla-central/rev/6cc287d1291e>
    * GitHub mirror: <https://github.com/mozilla/gecko-dev/commit/5a089f37d3dc6c6f69b20f474adcc48919e922eb>
  * [Bug 1680596](https://bugzilla.mozilla.org/show_bug.cgi?id=1680596) - Part 2: Replace the use of HTML menuitem in a LoginManagerContextMenu test r=tgiles: <https://hg.mozilla.org/mozilla-central/rev/4ff8babaa774>
    * GitHub mirror: <https://github.com/mozilla/gecko-dev/commit/cd589109a5d5a8c14ae93d25c7f815c3a71f8b91>
* \[mozilla.dev.platform\] **Intent to unship: HTML \<menuitem\> element and the context menu feature** (2020-12-08) (quoted, formatting theirs): <https://groups.google.com/g/mozilla.dev.platform/c/tc11BCenm2c>
  > It was removed from the HTML spec in 2017 because of the lack of implementer interest (https://github.com/whatwg/html/pull/2742). There is no other browser that implements this feature.
  >
  > Items to be removed:
  >
  > * `<menuitem>`
  > * The `type` attribute of `<menu>`
  > * The `onshow` event handler
  > * The `contextMenu` attribute of HTMLElement
  >
  > It will first be hidden behind the flag `dom.menuitem.enabled` and later will be completely removed.
  >
  > Bug to remove: https://bugzilla.mozilla.org/show_bug.cgi?id=1680596 and https://bugzilla.mozilla.org/show_bug.cgi?id=1372276.
* Bug 1372276 - **Remove HTML context menu (\<menu\> and \<menuitem\> tag) support** (Opened: 2017-06-12; Closed: 2022-06-23; Status: RESOLVED; Resolution: FIXED; Target Milestone: 103 Branch): <https://bugzilla.mozilla.org/show_bug.cgi?id=1372276>
  * [Bug 1372276](https://bugzilla.mozilla.org/show_bug.cgi?id=1372276) - Remove HTML menuitem. r=smaug,mconley,agi: <https://hg.mozilla.org/mozilla-central/rev/065b130fb59f>
    * GitHub mirror: <https://github.com/mozilla/gecko-dev/commit/bd0949737865f4c8d3f849dc62b3809d908e7593>
  * Documentation parent task: <https://github.com/mdn/content/issues/19707>
    * <https://github.com/mdn/content/pull/20421>
    * <https://github.com/mdn/browser-compat-data/pull/17734>
    * <https://github.com/mdn/browser-compat-data/pull/17793>
* <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem#browser_compatibility>
* Firefox release calendar (quoted abridged): <https://wiki.mozilla.org/Release_Management/Calendar>
  > **Future branch dates**
  > | Quarter | Release Date | Release     | ESR                   |
  > | ------: | :----------- | :---------- | :-------------------- |
  > | Q4 2022 | 2022-10-18   | Firefox 106 | Firefox 102.4         |
  > |         | 2022-11-15   | Firefox 107 | Firefox 102.5         |
  > |         | 2022-12-13   | Firefox 108 | Firefox 102.6         |
  > | Q1 2023 | 2023-01-17   | Firefox 109 | Firefox 102.7         |
  > |         | 2023-02-14   | Firefox 110 | Firefox 102.8         |
  > |         | 2023-03-14   | Firefox 111 | Firefox 102.9         |
  > | Q2 2023 | 2023-04-11   | Firefox 112 | Firefox 102.10        |
  > |         | 2023-05-09   | Firefox 113 | Firefox 102.11        |
  > |         | 2023-06-06   | Firefox 114 | Firefox 102.12        |
  > | Q3 2023 | 2023-07-04   | Firefox 115 | Firefox 102.13; 115.0 |
  > |         | 2023-08-01   | Firefox 116 | Firefox 102.14; 115.1 |
  > |         | 2023-08-29   | Firefox 117 | Firefox 102.15; 115.2 |
  > |         | 2023-09-26   | Firefox 118 | Firefox 115.3         |
  > | Q4 2023 | 2023-10-24   | Firefox 119 | Firefox 115.4         |
  > |         | 2023-11-21   | Firefox 120 | Firefox 115.5         |
  > |         | 2023-12-19   | Firefox 121 | Firefox 115.6         |
