### ISSUE TITLE
Menu entry does not show

### ISSUE THREAD

**Issue by asheiduk** [certainlyakey/Copy-current-page-URL-with-anchor#5]
There is no menu entry in the right click menu. 

Firefox 89.0 on Ubuntu 18.04 LTS.

example page: https://en.wikipedia.org/wiki/Wikipedia

**Comment by kernc** [comment]
Duplicate of https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/issues/4.

**Comment by certainlyakey** [comment]
Closing as a duplicate.
