### ISSUE TITLE
Excessive scrollbars

### ISSUE THREAD

**Issue by DenisKruchkov** [certainlyakey/Copy-current-page-URL-with-anchor#6]
When I have this extension enabled I have excessive scrollbars at pages where should be no such. 

![изображение](https://user-images.githubusercontent.com/87932607/128340325-d7938552-ff7b-42c2-88f8-e7457bec60a2.png)

Here you can see a Google start page which if fit should have no scroll bars. When I switch extension off and restart Firefox - scrollbars don't appear anymore.

**Comment by kernc** [comment]
What version, browser?

It's likely to do with the appended extra element: https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/blob/6641750737342348267aa74300956c4a0755798e/content.js#L10-L14

**Comment by certainlyakey** [comment]
Fixed by #7.
