### ISSUE TITLE
White gap on top of gmail

### ISSUE THREAD

**Issue by untitaker** [certainlyakey/Copy-current-page-URL-with-anchor#8]
When enabling this extension, a white gap shows on top of Gmail. The item `__copy_menu__` is responsible.

Aside, please use more descriptive IDs or classnames to make it easier to find the culprit browser extension. It was completely unclear from the developer console which extension added this element

![Screenshot 2022-04-26 at 20 16 24](https://user-images.githubusercontent.com/837573/165365903-e287e5c9-6012-4759-a77e-4d670bc1bdd6.png)

**Comment by kernc** [comment]
This is fixed in PR https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/pull/7, which makes the addon compatible with newer versions of Firefox. Please review.

**Comment by certainlyakey** [comment]
Fixed by #7.
